# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62a076e7f6740ca965dbdebb11bddaf0204e78e86aff8a037b914b06d1d2e0b177363e961720213a9c6fd847aa64f0b0923c6959975beda49282e38aa2a43f56

test:
  secret_key_base: f2c5b12836c603b5b7b48baad05b93d706380cbf707c27f51aae383821eb6b28173fbfa7ca46c39a666fa1392484ded038aacaa81beb2c44f2a637948ca4fa5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
